
DROP TABLE IF EXISTS passage;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS seance;
DROP TABLE IF EXISTS salle;
DROP TABLE IF EXISTS cinema;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS subscribe;

DROP TABLE IF EXISTS movie_actor;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS actor;