CREATE TABLE IF NOT EXISTS subscribes (
id INT UNSIGNED AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
reduce TINYINT UNSIGNED NOT NULL ,
price DECIMAL(5,2)NOT NULL,
priority BOOLEAN DEFAULT 0,
reserved_place BOOLEAN DEFAULT 0,
PRIMARY KEY (id),
CONSTRAINT chk_price CHECK (price > 0),
CONSTRAINT unq_name UNIQUE(name)
);



CREATE TABLE IF NOT EXISTS users (
id INT UNSIGNED AUTO_INCREMENT,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
surname VARCHAR(255 )NOT NULL,
email VARCHAR(255) NOT NULL,
passwrd VARCHAR(255) NOT NULL,
id_sub INT UNSIGNED DEFAULT NULL,
end_sub DATE DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT fk_id_sub_id FOREIGN KEY (id_sub) REFERENCES subscribes(id),
CONSTRAINT unq_surname UNIQUE(surname),
CONSTRAINT unq_email UNIQUE(email)
);
