DROP TABLE IF EXISTS users ;
DROP TABLE IF EXISTS subscribes ;

DROP PROCEDURE IF EXISTS p_add_subscribes;
DROP PROCEDURE IF EXISTS p_add_users;
DROP PROCEDURE IF EXISTS p_add_sub_user;
DROP PROCEDURE IF EXISTS p_delete_sub_user;

DROP FUNCTION IF EXISTS f_id_sub;





